name: Test code and app
on: [push, pull_request]
jobs:
  test_model:
    name: Test processed code and model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        id: checkout
        uses: actions/checkout@v3

      - name: Environment setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1
        
      - name: Install packages
        run: poetry install

      - name: Run tests
        run: poetry run pytest 